[package]
name = "rasteroids"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy-inspector-egui = "0.12.0"
bevy_rapier2d = "0.16.2"
rand = "0.8.5"
